### ISSUE TITLE
Initial stepsize not exposed in LBFGS constructor [question/bug?]

### ISSUE THREAD

**Issue by erdmann** [google/jaxopt#176]
I see that [`LbfgsState`](https://github.com/google/jaxopt/blob/4b66e88ce9ee83cc78ffc68afd949c4202d164ec/jaxopt/_src/lbfgs.py#L134:7) contains a `stepsize` and that [`LBFGS.init_state`](https://github.com/google/jaxopt/blob/4b66e88ce9ee83cc78ffc68afd949c4202d164ec/jaxopt/_src/lbfgs.py#L206) hard-codes it to 1.  I also see that the [`LBFGS.update` method](https://github.com/google/jaxopt/blob/4b66e88ce9ee83cc78ffc68afd949c4202d164ec/jaxopt/_src/lbfgs.py#L265) performs a line search in which the initial step size is set from this LBFGS state.

I have a particularly ill-conditioned problem that requires tiny initial steps, but I was surprised that the initial stepsize could not be set in the LBFGS constructor or elsewhere as far as I could see.  Is this an oversight or an intentional part of the design?  If it's intentional, is there an idiomatic way to set an initial stepsize when using `LBFGS.run` that I have overlooked?

Thanks in advance, and thanks for a really cool library.

**Comment by quattro** [comment]
I'm finding myself in a similar position, even with x64 enabled. The LBFGS implementation initial stepsize is `1.0 * increase_factor` which results in a large number of iterations compared to the SciPy wrapper implementation (see [here](https://colab.research.google.com/drive/1BKLITtJuiD4o6ETzTpIGlbXbHGHzLMfl?usp=sharing) for example). Without x64 enabled it fails to proceed beyond its initialization due to `nan`/ model misspecification.

It would be fantastic to have a more flexible initialization at some point in the future. Thank you and the team for developing such a useful library.

**Comment by mblondel** [comment]
What do you think of replacing `init_stepsize = state.stepsize * self.increase_factor` with `init_stepsize = min(state.stepsize * self.increase_factor, 1.0)` as a safegard? (see [this line](https://github.com/google/jaxopt/blob/main/jaxopt/_src/lbfgs.py#L265))

**Comment by quattro** [comment]
Thanks @mblondel . It might need to wait until configurable LineSearch objects can be initialized and passed in to create a more flexible starting point.

I found a simpler example where LBFGS chokes compared to other methods. See [here](https://colab.research.google.com/drive/1HZQbenKunjodG7WBut9BKpjCDV83SsKF?usp=sharing)

**Comment by mblondel** [comment]
Glad to hear that and sorry it took some time! 

Thanks #236 and #239, it's now possible to set the initial step size using the `max_stepsize` option. 

I am closing this issue but feel free to re-open if necessary.
