### ISSUE TITLE
Issue with `scan` + OptaxSolver(., ., has_aux=True)

### ISSUE THREAD

**Issue by pharringtonp19** [google/jaxopt#258]
I believe the following lines of code could be tweaked so that we can use `OptaxSolver(., ., has_aux=True)` inside an update funcation that we pass to `jax.lax.scan` (an example of this type of training loop is shown below). It appears that the line `aux=None` is the problem as "scan carry output and input must have same type structure"

https://github.com/google/jaxopt/blob/ea89be7b42fe78eb1abfefd74bd872429eeda39b/jaxopt/_src/optax_wrapper.py#L94-L98

```
 @partial(jax.jit, static_argnums=(2,))
  def train(theta, state, epochs):

      def update(carry, t):
          theta, state = carry 
          theta, state = solver.update(params=theta, state=state, init_inner= jnp.zeros(X.shape[1]), data=data)
          return (theta, state), (state.value, state.aux)
      (theta_opt,_), (val_losses, train_losses) = jax.lax.scan(update, (theta, state), None, length=epochs)
      return val_losses, train_losses
```

**Comment by mblondel** [comment]
Thanks for the bug report. I agree this should be fixed! The issue is that we need a way to figure out the type of `aux`. Perhaps we can use [eval_shape](https://jax.readthedocs.io/en/latest/_autosummary/jax.eval_shape.html#jax.eval_shape) but not 100% sure it will work with pytrees. Another way is to just call `fun` within `init_state` to retrieve `aux` (this will cost one function evaluation). See also #116

**Comment by pharringtonp19** [comment]
@mblondel What do you think about the idea of having `solver.update` return `aux` directly?

**Comment by mblondel** [comment]
@pharringtonp19  PR #273 should hopefully fix the issue.

**Comment by pharringtonp19** [comment]
@mblondel Much appreciated!
