### ISSUE TITLE
ScipyMinimize(method="TNC") is broken

### ISSUE THREAD

**Issue by terhorst** [google/jaxopt#536]
Scipy's TNC implementation does not set the number of Jacobian evaluations  in the `ScipyOptimizeResult`, which causes the jaxopt wrapper to throw:
```
ScipyMinimize(method="TNC", fun=lambda x: x**2).run(1.0)
# Traceback (most recent call last):     
# ...
# KeyError: 'njev'
```
I'm running jaxopt 0.8 and Scipy 1.11.2.

**Comment by mblondel** [comment]
I believe this is the same issue as ##531. 

@zaccharieramzi Looks like some attributes are missing depending on the same solver.

**Comment by zaccharieramzi** [comment]
@mblondel indeed it's probably the same thing.

The [scipy doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) is a bit elusive on the topic since it says that `njev` is always accessible normally.

I will try to come up with a quick fix.
