### ISSUE TITLE
Jacobian Estimate Error 

### ISSUE THREAD

**Issue by pharringtonp19** [google/jaxopt#57]
Based on section 2.3 of the [paper](https://arxiv.org/pdf/2105.15183.pdf), I am curious to see how the jacobian error varies as I change `x_t`, holding `\theta` fixed (to use notation from the paper).

I thought this would be possible for instance by using `custom_jvp` and overwriting the `primal_out` with `x_t`. This would require me, though, to add `x_t` as an auxiliary argument to `custom_jvp`. I was wondering if this is possible.

**Comment by mblondel** [comment]
We have an updated version of the paper coming soon where we did exactly that.

![image](https://user-images.githubusercontent.com/233706/136223881-7ad66fd5-a4a4-4f6b-ad48-53b4800eef48.png)

The simplest is to just set `maxiter=t` in `GradientDescent` to force it to exit at some iteration `t`. Otherwise you can also use `jaxopt.implicit_diff.root_jvp`.

**Comment by pharringtonp19** [comment]
@mblondel That is a great figure! Thanks for the help
